version: 2.1
jobs:
  TEST:
    working_directory: ~/src
    docker:
      - image: circleci/node:10
        environment:
          PORT: 3000
    
    steps:
      - checkout
      - run: sudo npm install -g npm@latest
      - run: sudo npm install -g yarn
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # - run: docker-compose up -d
      # run tests
      - run: yarn lint
      - run: yarn test
workflows:
  version: 2
  TEST:
    jobs:
      - TEST